# Generated by Django 3.1.7 on 2021-03-25 04:15

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[6-9]\\d{9}$'), code='invalid', message='Enter a valid 10 digit mobile number')])),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(re.compile('^[1-9][0-9]{5}$'), code='invalid', message='Enter a valid 6 digit pincode')])),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=300)),
                ('summary', models.TextField(max_length=60)),
                ('document', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], code='invalid_file_format', message='Uploaded document is not a pdf')])),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('BOND', 'BOND'), ('CERTIFICATE', 'CERTIFICATE'), ('LICENSE', 'LICENSE'), ('PASSPORT', 'PASSPORT'), ('CONTRACT', 'CONTRACT')], max_length=42)),
            ],
        ),
    ]
